# coding: utf-8

"""
    bampli-api

    The API for the Business Amplifier project.  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: josemotta@bampli.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.company_address import CompanyAddress  # noqa: E501
from swagger_client.rest import ApiException


class TestCompanyAddress(unittest.TestCase):
    """CompanyAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyAddress(self):
        """Test CompanyAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.company_address.CompanyAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
